services:
  - type: web
    name: battery-predictor-api
    env: python
    region: oregon
    plan: free
    repo: jbyiringiro/linear_regression_model
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker prediction:app --chdir summative/API --bind 0.0.0.0:$PORT"
    rootDir: .
    autoDeploy: true