services:
  - type: web
    name: battery-predictor-api
    env: python
    region: oregon
    plan: free
    repo: jbyiringiro/linear_regression_model
    branch: main
    buildCommand: "pip install -r summative/API/requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker prediction:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
    rootDir: .
    autoDeploy: true